-- orders.id passa a ser gerado pelo banco (identity), começando do max atual.
-- Elimina a colisão de id do addOrder (max+1 no client) sob concorrência.
do $$
declare mx bigint;
begin
  select coalesce(max(id), 1042) into mx from orders;
  execute 'alter table orders alter column id add generated by default as identity (start with ' || (mx + 1) || ')';
end $$;
