-- cash_sessions.id passa a ser gerado pelo banco (identity), começando do max atual.
-- Elimina a colisão de id do openCash (max+1 no client) sob concorrência.
do $$
declare mx bigint;
begin
  select coalesce(max(id), 1042) into mx from cash_sessions;
  execute 'alter table cash_sessions alter column id add generated by default as identity (start with ' || (mx + 1) || ')';
end $$;
